### ISSUE TITLE
MODE 3

### ISSUE THREAD

**Issue by a7hybnj2** [rocatj12/MacUninstaller#1]
I just came across this script. I was using [appcleaner](https://freemacsoft.net/appcleaner/) but wanted to find a open version. I like the look of this so far.

I am just curious what are your plans for MODE3?

**Comment by rocatj12** [comment]
Mode 3 is still under works.

I want to reserve Mode 2 for searching common support locations, adding as they become more prevalent, while Mode 3 will be more of a system-wide scan. It needs to be refined a lot to be sure to exclude important system files to maintain a healthy operating system.
