### ISSUE TITLE
Invalide Mode

### ISSUE THREAD

**Issue by a7hybnj2** [rocatj12/MacUninstaller#2]
I tried to run with `-m 2` and `-m Standard` and they were both listed as invalid. I just then tried to run it without the -m because 2 was default anyway.

What did I do wrong? What are the correct mode syntax?

**Comment by rocatj12** [comment]
Thank you for your feedback. At the time of the previous release, it was still under development, (should've used more appropriate version numbers) but the issue has been more or less resolved in the current release with a slight overhaul of the code. (Appropriate version numbers have been assigned).
